### ISSUE TITLE
Error handling Events by facet..

### ISSUE THREAD

**Issue by biahoi** [mudgen/Diamond#4]
Hi @mudgen ,
I have added few facets to my diamond successfully. Truffle Testing runs smooth. 
But as I added this facet, here comes a problem:
I want to put all events into one Facet. The Facet code is like this:

F_events.sol:
```
pragma solidity ^0.6.12;
// SPDX-License-Identifier: MIT

import "./DiamondStorageContract.sol";

contract F_events is DiamondStorageContract{
  event simpleEvent(string eventNotice);
}
```

The testing Code is this:

```
...
    it('should add F_events functions', async () => {
      const selectors = getSelectors(f_events)
      addresses.push(f_events.address)
      result = await diamondFacet.methods.diamondCut([f_events.address + selectors]).send({ from: web3.eth.defaultAccount, gas: 1000000 })
      result = await diamondLoupeFacet.methods.facetFunctionSelectors(addresses[7]).call()
      assert.equal(result, '0x' + selectors)
    })

```
and it give this error:
![image](https://user-images.githubusercontent.com/42067513/89397030-8902ef00-d739-11ea-88e1-35d50ac4e08a.png)

**Comment by biahoi** [comment]
It seems that although the test can nos pass this assert check, but when i comment out this assert check, The facet still works.. Am I right?

**Comment by mudgen** [comment]
Are you sure that `addresses[7]` and `f_events.address` are the same address?   I think you will have to show all your source code to debug this further.

**Comment by biahoi** [comment]
No.. addresses[7] and f_events.address are not the same. :-( 
I am having the assertion test commented out for Testing on diamond cut for F_events.
And,  there are 2 events are declared inside F_events, but few more events inside F_events I had to comment out, otherwise It don't deploy either..
Please help..
https://github.com/biahoi/Diamond_GambleEngine01.git

**Comment by biahoi** [comment]
Hi @mudgen ,
I found that after this line:
`f_events = new web3.eth.Contract(F_events.abi, diamond.address)`

f_events doesn't have .address anymore; It has only  f_events._address   which is the same as diamond.address.

**Comment by mudgen** [comment]
I fixed an issue with events which I think may be been causing this problem.
