### ISSUE TITLE
Can "immutable" functions be removed?

### ISSUE THREAD

**Issue by arialblack14** [mudgen/diamond#4]
I am trying to understand this `require` statement:

```solidity
 // an immutable function is a function defined directly in a diamond
require(
    _facetAddress != address(this),
    "LibDiamondCut: Can't remove immutable function"
);
```

It is implemented in `LibDiamond.removeFunction()` that is being called by `replaceFunctions()` and `removeFunctions()` in `LibDiamond.sol` (e.g. [here](https://github.com/mudgen/diamond-3-hardhat/blob/main/contracts/libraries/LibDiamond.sol#L155-L156)).
@mudgen Could you please explain how someone could remove/replace a function defined in a diamond?
Or has this check been added as a sanity check according to [EIP-2535](https://eips.ethereum.org/EIPS/eip-2535)?
Thank you

**Comment by mudgen** [comment]
Someone could not remove a function that is defined directly in a diamond proxy.  But such functions still need to be returned by the loupe functions which means they need to be added to storage with the address `address(this)`.  So the require statement checks if there is an attempt to remove an immutable function and throws an error if so.

[The EIP2535 standard says this:](https://eips.ethereum.org/EIPS/eip-2535#implementation-points)

> All immutable functions must be emitted in the DiamondCut event as new functions added. And the loupe functions must return information about immutable functions if they exist. The facet address for an immutable function is the diamond’s address. Any attempt to delete or replace an immutable function must revert.

**Comment by arialblack14** [comment]
@mudgen That makes total sense. Thank you for clearing that out!

I was trying to understand why that check wasn't added on the `LibDiamond.addFunctions()` which makes it possible to add `address(this)` as a `facetAddress`. Then noone will be able to remove or replace that function.
But it is intended behaviour according to the EIP.
